name: hero_hub
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  #Core
  flutter_bloc:
  get_it: #Simple direct Service Locator
  rxdart: #RxDart is an implementation of the popular reactiveX api for asynchronous programming, leveraging the native Dart Streams api.
  fpdart: #Either =>Functional programming in Dart and Flutter.
  shared_preferences: ^2.2.2 #Flutter plugin for reading and writing simple key-value pairs.
  # google_mobile_ads:
  cached_network_image: ^3.3.0
  connectivity_plus: ^6.0.3
  url_launcher:

  # Apis
  dio: ^5.3.3
  retrofit: ^4.0.3
  freezed_annotation:
  json_annotation: ^4.8.1
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1

  #UI
  another_flushbar: ^1.12.30
  flutter_svg:
  flutter_screenutil:
  # flutter_spinkit:
  # google_fonts:
  # lottie: ^2.6.0
  # iconsax: ^0.0.8
  talker_flutter: ^4.1.5

  #Language  // or use  flutter pub add flutter_localizations --sdk=flutter
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1 # for the policy dialog => A Markdown renderer for Flutter. Create rich text output, including text styles, tables, links, and more, from plain text data formatted with simple Markdown tags.
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: # dart run build_runner build --delete-conflicting-outputs
  json_serializable: ^6.7.1 # Automatically generate code for converting to and from JSON by annotating Dart classes
  freezed:
  flutter_lints:
  very_good_analysis: ^5.1.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  rename:

# #to make native splash screen
# # 1) change path image_path
# # 2) run commened -> dart run flutter_native_splash:create --path=flutter_native_splash.yaml
#   flutter_native_splash: ^2.1.1
# flutter_native_splash:
#   background_image: assets/image/splash_background.png # choose one color or background
#   color: "#ffffff"
#   image: assets/icons/icon.png

# # to change icon
# # 1) change path image_path
# # 2) run commened -> flutter pub run flutter_launcher_icons:main
#   flutter_launcher_icons: ^0.9.2
# flutter_launcher_icons:
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/images/play_store_512.png"
#   adaptive_icon_foreground: "assets/images/play_store_512.png"
#   adaptive_icon_background: "#ffffff"

#rename rename setAppName --targets ios,android --value "......"

#native splash dart run flutter_native_splash:create
#native splash from file #- dart run flutter_native_splash:create --path=flutter_native_splash.yaml

flutter:
  assets:
    - lang/ar.json
    - lang/en.json
    - assets/icons/
    - assets/images/
    - assets/animations/lotties_anim/
    - assets/svgs/
    - assets/links/
  uses-material-design: true

  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
