// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0lpIKeQLfSRAXgF8Txlc9RVmWM4ODe84',
    appId: '1:1048385838970:web:f5eaa07c0164c5d23c00c3',
    messagingSenderId: '1048385838970',
    projectId: 'hero-hub-ba77b',
    authDomain: 'hero-hub-ba77b.firebaseapp.com',
    storageBucket: 'hero-hub-ba77b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtLJqZeSwx0CjTpN1f4QW6StdCgWLRevU',
    appId: '1:1048385838970:android:95de277597f9ac4a3c00c3',
    messagingSenderId: '1048385838970',
    projectId: 'hero-hub-ba77b',
    storageBucket: 'hero-hub-ba77b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4KfQHbkHuABCLYukamrydoiTa9GF4-Q',
    appId: '1:1048385838970:ios:0f98699c0d4e894f3c00c3',
    messagingSenderId: '1048385838970',
    projectId: 'hero-hub-ba77b',
    storageBucket: 'hero-hub-ba77b.appspot.com',
    iosBundleId: 'nz.dev.herohub.heroHub',
  );
}
